namespace: wooglife

deployment:
  name: telegram-bot
  image: ghcr.io/woog-life/telegram-bot:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: telegram-bot
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 300m
    memory: 500Mi
  updateStrategy: Recreate

cronjob:
  name: telegram-updater
  image: ghcr.io/woog-life/telegram-updater:__TAG__
  imagePullPolicy: Always
  schedule: "0 7 * * *"
  timeZone: "Europe/Berlin"
  arg: "update"
  backoffLimit: 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  restartPolicy: Never
  labels:
    app: telegram-updater
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

secret:
  # we're reusing the existing token so this is "fine"
  name: telegram-updater-token

configmap:
  name: telegram-bot
  woog:
    apiUrl: http://backend
  notifierIds: "-1001397708243"
  alertIds: "139656428"
