namespace: wooglife

deployment:
  name: telegram-bot
  image: ghcr.io/woog-life/telegram-bot:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: telegram-bot
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 300m
    memory: 500Mi
  updateStrategy: Recreate

cronjob:
  name: telegram-updater-v2
  image: ghcr.io/woog-life/telegram-bot:__TAG__
  imagePullPolicy: Always
  schedule: "0 7 * * *"
  timeZone: "Europe/Berlin"
  command: "java"
  args:
  - "-jar"
  - "main.jar"
  - "update"
  backoffLimit: 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  restartPolicy: Never
  labels:
    app: telegram-updater-v2
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

secret:
  # we're reusing the existing token so this is "fine"
  name: telegram-updater-token

configmap:
  name: telegram-bot
  woog:
    apiUrl: http://backend
  notifierIds: "-1001397708243"
  alertIds: "139656428"
  ignoreIdsInUpdate:
    - "a2595d6a-a6fc-4ee3-86b4-871f32f28b4c" # santander
    - "bedbdac7-7d61-48d5-b1bd-0de5be25e953" # potsdam
    - "359e0773-e7ee-4ee0-8c11-a9eb5082d899" # heraklion
    - "4ddb043b-d0d2-44a5-b321-6efbaacf98a0" # sorrento
