apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  API_URL: "{{ .Values.configmap.woog.apiUrl}}"
  NOTIFIER_IDS: "{{ .Values.configmap.notifierIds }}"
  ALERT_IDS: "{{ .Values.configmap.alertIds }}"
