apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  timeZone: "{{ .Values.cronjob.timeZone }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- range $k, $v := .Values.cronjob.labels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        spec:
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          containers:
          - name: {{ .Values.cronjob.name }}
            image: {{ .Values.cronjob.image }}
            imagePullPolicy: {{ .Values.cronjob.imagePullPolicy }}
            args:
            - {{ .Values.cronjob.arg }}
            envFrom:
              - secretRef:
                  name: {{ .Values.secret.name }}
              - configMapRef:
                  name: {{ .Values.configmap.name }}
            resources:
              requests:
                cpu: {{ .Values.cronjob.requests.cpu }}
                memory: {{ .Values.cronjob.requests.memory }}
              limits:
                cpu: {{ .Values.cronjob.limit.cpu }}
                memory: {{ .Values.cronjob.limit.memory }}
